name: CI
on: [push]
jobs:
  build-on-unix:
    strategy:
      matrix:
        java: [8,11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: topic-queue-example ${{ matrix.os }} java-${{ matrix.java }}
    steps:
    - name: Git clone
      uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build and test gradle app
      uses: eskatos/gradle-command-action@v1
      with:
        #build-root-directory: .
        gradle-version: ${{ matrix.gradle-version }}
        arguments: clean build -S -Dsleep=50
    - run: ./mvnw -f topic-queue-example
